### ISSUE TITLE
报错cannot import name 'ParamSpec' from 'typing"

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [ssttkkl/nonebot-plugin-majsoul#1]
![image](https://user-images.githubusercontent.com/70925546/206398797-8b5cec89-1639-4a1a-a6d6-497ce4094388.png)

**Comment by ssttkkl** [comment]
用到py3.10才有的东西导致的兼容性问题，等我改了再发个包吧
________________________________
From: Agnes Digital ***@***.***>
Sent: Thursday, December 8, 2022 4:55:26 PM
To: ssttkkl/nonebot-plugin-majsoul ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ssttkkl/nonebot-plugin-majsoul] 报错cannot import name 'ParamSpec' from 'typing" (Issue #1)


[image]<https://user-images.githubusercontent.com/70925546/206398797-8b5cec89-1639-4a1a-a6d6-497ce4094388.png>

―

**Comment by ssttkkl** [comment]
已修复，请升级0.0.5版本
