### ISSUE TITLE
查询错误：pydantic.error_urappers.ValidationError: 1 validation error for PlayerExtendedStats默听率 none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [ssttkkl/nonebot-plugin-majsoul#2]
pydantic.error_urappers.ValidationError: 1 validation error for PlayerExtendedStats默听率
none is not an allowed value (type=type_error.none.not_allowed)
![image](https://user-images.githubusercontent.com/70925546/207247861-f0ef7c0a-1a15-4e9c-8c2a-1f54342866d5.png)

**Comment by ssttkkl** [comment]
能否提供下你查询使用的ID

**Comment by Umamusume-Agnes-Digital** [comment]
雀魂三麻查询 岩永琴子丶

**Comment by ssttkkl** [comment]
版本0.1.2已修复
原因是某个字段数值为0的时候牌谱屋api返回的是null
